/*
 * File: app/view/HomeContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Glasgow2014.view.HomeContainer', {
    extend: 'Ext.Panel',
    xtype: 'homepanel',
    
    
fullscreen: true,

    
    config: {
    	
    	title:'Home',
    	iconCls:'info',
    	cls:'homepage',
  layout:{
                type:'vbox',
                align:'center'
           },
    
        items: [
		{
                dock: 'top',
                xtype: 'toolbar',
                title: 'Home',
		        cls:'title'
                },
      
            {
            	
                html: [ '<br/>',
			"<div class='myContainer'>",
			'<br/>',
			'<br/>',
           	//'<img src="resources/images/home.png" />',
                       	"<div >Developer:  Andrea Daly  Email: andiedaly@gmail.com</div>",
                       
				
                       	'<br/><br/>',
				
			
                        '</div>'
                       	//'<img src="resources/images/home.png" height="500px" class="jqPuzzle"/>'
                      //  '<img  class="myCls"/>'
					].join("")
                
            }
        ]
    }
});