/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Glasgow2014.view.MyPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.myPanel',

    requires: [
        'Ext.Button',
        'Ext.XTemplate'
    ],

    config: {
        id: 'myPanelId',
        styleHtmlContent: true,
        tpl: [
            '<div>',
            '<h3>{venue}</h3>',
            '<p>Address is {address}</p>',
            //'<p>Key is {key}</p>',
            //'<p>{text}</p>',
            '</div>'
        ],
        
    


        items: [
            {
                xtype: 'button',
                centered: true,
                cls: 'btnAction',
                id: 'pubsButtonId',
                styleHtmlContent: true,
                ui: 'action',
                action: 'buttonTap',
                parmListId: '{venue}'
            }
        ]
    }

});