/*
 * File: app/view/MyTabPanel.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Glasgow2014.view.MyTabPanel', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.mytabpanel',

    requires: [
        'Ext.tab.Bar',
        'Glasgow2014.view.Main2'
    ],

    config: {
        tabBar: {
            docked: 'bottom',
            layout: {
                type: 'hbox',
                pack: 'center'
            }
        },
        items: [
            {
                xtype: 'homepanel',
                title: 'Home',
                iconCls: 'home'
            },
            {
                xtype: 'scheduletreeview',
                title: 'Schedule',
                iconCls: 'info'
            },
          /* {
                xtype: 'mainnav',
                title: 'Pubs',
                iconCls: 'info'
            },*/
            {
                xtype: 'main2',
                title: 'Pit Stops',
                iconCls: 'info'
            }
        ]
    }

});