/*
 * File: app/view/ScheduleTreeView.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Glasgow2014.view.ScheduleTreeView', {
    extend: 'Ext.dataview.NestedList',
    alias: 'widget.scheduletreeview',

    config: {
        id: 'test',
        detailCard: {
            xtype: 'myPanel'
        },
        store: 'ScheduleTreeStore',
        title: 'Schedule',
        listeners: [
            {
                fn: 'onNestedlistLeafItemTap',
                event: 'leafitemtap'
            }
        ]
    },

    onNestedlistLeafItemTap: function(nestedlist, list, index, target, record, e, eOpts) {
        var detailCard = this.getDetailCard();

        //var me = this;
        var node = Ext.getCmp('test').getLastNode();
        //var test = hasParent(Ext.getCmp('test').getLastNode());
        //var nodetest=this.goToNode(test);
        //var me = this;

        //var test=hasParent(me);
                   // detailCard.setHtml('You selected: ' + test.get('text'));
        //detailCard.setHtml('You selected: ' + node.parentNode.get('venue'));

        //detailCard.setTpl(node.parentNode.get('venue'));
          // define a sample data object
        var myData = {
        venue: node.parentNode.get('venue'),
        address: node.parentNode.get('address'),
       // key:node.node.get('key'),
        text:node.get('text')

        };
        // get a pointer to the component instance
        //var myCmp = Ext.ComponentQuery.query('#mycomponent')[0];
        // transmit data to the component and process through the template
        detailCard.setData(myData);


        //record.get('venue')
    }

});