/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides


Ext.Loader.setPath({
				'Ext': 'touch/src',
				'Glasgow2014': 'app'
});

Ext.Loader.setConfig({

});


Ext.application({
	
	requires: [
	           'Ext.MessageBox',
	           'Glasgow2014.util.Util'
	          // 'Glasgow2014.config.Config'
	           ],
    models: [
        'Business',
        'ScheduleTree',
        'Category',
        'Place',
        'SchedulePlace'
    ],
    stores: [
        'BusinessStore',
        'ScheduleTreeStore',
        'Categories',
        'Places',
        'SchedulePlaces'
    ],
    views: [
        'MainNav',
        'ListContainer',
        'DetailPanel',
        'MyTabPanel',
        'ScheduleTreeView',
        'MyPanel',
        'HomeContainer',
        'MapContainer',
        'Main2',
        'PlaceList',
        'Categories',
        'PlaceMap',
        'Places',
        'details.Main',
		'details.Info',
		'details.Gallery',
		'details.Review',
		'details.GalleryCarousel',
		'SchedulePlaceList'
    ],
    controllers: [
        'Business',
        'App',
        'PlaceDetails'
    ],
    name: 'Glasgow2014',

    launch: function() {
        console.log("Application launch");
        //Ext.fly('appLoadingIndicator').destroy();
        //Ext.create('Glasgow2014.view.MyTabPanel', {fullscreen: true});
        console.log("Application launch truem");
      

        Ext.create('Glasgow2014.view.MyTabPanel', {fullscreen: true});
    }

});
