/*
 * File: app/controller/Business.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Glasgow2014.controller.Business', {
    extend: 'Ext.app.Controller'
    
   /* requires: ['Ext.device.Geolocation', 'Ext.Map'],
    util: Glasgow2014.util.Util,

    config: {
        refs: {
            dataList: '#dataList',
            listCard: '#listCard',
            mainNav: 'mainnav',
            categoriesList: 'categories',
            main2:'main2',
            detailCard: 'detailpanel',
           
            
            placesDetailCard: 'placesDetailPanel',
            
            
        },

        control: {
            "#dataList": {
                itemtap: 'onListItemTap'
            },
            "detailpanel > map": {
                activate: 'onMapActivate'
            },
            "#pubsButtonId": {
                tap: 'onButtonTap'
            }
           
            
        }
    },

    onListItemTap: function(dataview, index, target, record, e, eOpts) {
        


                var map,
                        info,
                        details;

                    if (record) {
                        details = Ext.create('Glasgow2014.view.DetailPanel', {
                            title: 'Details'
                        });

                        // stash info for later use by the map card
                        map = details.child('#detailMap');
                        map._record = record;

                        // set the info
                        info = details.child('#contact').child('#info');
                        info.child('#photo').setData(record.data);
                        info.child('#data').setData(record.data);

                        this.getMainNav().push(details);
                    }
    },
    
  
    onMapActivate: function(newActiveItem, container, oldActiveItem, eOpts) {
         var map = newActiveItem,
                       record = map._record,
                       lat = record.get('latitude'),
                       lng = record.get('longitude'),
                       centerMap = Ext.Function.createDelayed(function() {
                           map.setMapOptions({
                               zoom: 18
                           });
                           map.setMapCenter({
                               latitude: lat,
                               longitude: lng
                           });
                       }, 250),
                       geocoder, loc;
                    if (lat && lng) {
                       centerMap();
                    } else {
                       geocoder = this._geocoder || (this._geocoder = new google.maps.Geocoder());
                       geocoder.geocode(
                           {address: [
                               record.get('address1'),
                               record.get('address2'),
                               record.get('address3'),
                               record.get('city'),
                               record.get('state_code'),
                               record.get('zip')
                           ].join(', ')},
                           function(results, status) {
                               if (status == google.maps.GeocoderStatus.OK) {
                                   loc = results[0].geometry.location;
                                   lat = loc.lat();
                                   lng = loc.lng();
                                   record.set('latitude', lat);
                                   record.set('longitude', lng);
                                   centerMap();
                               } else {
                                   Ext.Msg.alert("Could not find location: " + status);
                               }
                           }
                       );
                    }
    },

    onButtonTap: function(button, e, eOpts) {
       
        /*var venueLocation={

            long:-4.251806,
            lat: 55.864236999999996

        };*/

       /* var mylong=-4.251806;
        var mylat= 55.864236999999996;
         var me = this;






                   /* var store = Ext.data.StoreManager.lookup('BusinessStore'),
                        yelpKey = 'On6hqIYZ7oNJMiuMEOIyTQ',
                        url = 'http://api.yelp.com/business_review_search' +
                        '?ywsid=' + yelpKey +
                        '&term=Bars' +

                        '&lat=' + mylat +
                        '&long=' + mylong;

                
                    store.getProxy().setUrl(url);
                    store.load();*/
        //this.getMainNav().push({xtype: 'listcontainer'});

        //console.log("test");
        //Ext.Viewport.animateActiveItem({xtype: 'mapcontainer'},{type: 'slide',direction: 'left'});
        // this.getMainNav().push({xtype: 'myPanel'});
       
 /*   },

    getLocation: function(callback) {
        if (navigator && navigator.geolocation) {
                            navigator.geolocation.getCurrentPosition(function(position) {
                                callback(position);
                            }, function(error) {
                                // give a warning for error
                            });
                        }
    },

  /*  launch: function() {
    	
    	
        var me = this;
        

                    Ext.Viewport.setMasked({ message: 'Loading...' });
                    // Get the user's location
                    
                    
                    
              
                    me.getLocation(function (location) {
                    	//var mystore = Ext.data.StoreManager.lookup('Categories');
                    	//mystore.load();
                        // Use Yelp to get the business names
                        me.getBusinesses(location, function (store) {
        
                            // Bind data to the list and display it
                            me.getDataList().setStore(store);
                           // Ext.Viewport.add(Ext.create('Glasgow2014.view.Main2'));
                            Ext.Viewport.setMasked(false);
                        });
                        
                       
                                                
                    });
    },

   /* getBusinesses: function(location, callback) {
         // Note: Obtain a Yelp API key by registering (for free)
                    // with Yelp at http://www.yelp.com/developers/getting_started/api_overview
                    // (in this app, we use the Review Search API v1.0)
                    var store = Ext.data.StoreManager.lookup('BusinessStore'),
                        yelpKey = 'On6hqIYZ7oNJMiuMEOIyTQ', // Enter your Yelp API key here
                        url = 'http://api.yelp.com/business_review_search' +
                        '?ywsid=' + yelpKey +
                        '&term=Bars' +
                        '&lat=' + location.coords.latitude +
                        '&long=' + location.coords.longitude;
                        //'&lat=' + venueLocation.lat +
                        //'&long=' + venueLocation.long;

                
                    store.getProxy().setUrl(url);
                    store.load(function() {
                        callback(store);
                    });
    }*/
    
   
    
    
        
    	

});